name: in_app_provisioning_example
description: Demonstrates how to use the in_app_provisioning plugin.
version: 0.0.1

publish_to: 'none' 

environment:
  sdk: ">=2.14.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  in_app_provisioning:
    path: ../

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
