let CHANNEL_NAME: String = "in_app_provisioning"
let INIT_ENROLLMENT: String = "initiate_enrollment"
let IS_PASSKIT_AVAILABLE: String = "is_passkit_available"
let PASSVIEW_DATA: String = "passview_data"
let PROVISIONING_PAYLOAD: String = "provisioning_payload"
